apiVersion: v1
kind: ConfigMap
metadata:
  name: keycloak-config
data:
  KC_BOOTSTRAP_ADMIN_USERNAME: admin
  KC_BOOTSTRAP_ADMIN_PASSWORD: admin
  KC_HEALTH_ENABLED: "true"
  KC_HOSTNAME_STRICT: "false"
  KC_HOSTNAME_STRICT_HTTPS: "false"
  KC_HTTP_ENABLED: "true"
  
  # Realm configuration
  realm.json: |
    {
      "realm": "KDEX Proxy",
      "enabled": true,
      "registrationAllowed": false,
      "clients": [
        {
          "clientId": "kdex-proxy",
          "enabled": true,
          "protocol": "openid-connect",
          "publicClient": false,
          "standardFlowEnabled": true,
          "implicitFlowEnabled": false,
          "directAccessGrantsEnabled": true,
          "serviceAccountsEnabled": true,
          "authorizationServicesEnabled": true,
          "redirectUris": ["http://proxy.docker.localhost/~/o/oauth/callback"],
          "webOrigins": ["*"]
        }
      ],
      "roles": {
        "realm": [
          {
            "name": "user",
            "description": "Regular user role"
          },
          {
            "name": "admin",
            "description": "Administrator role"
          }
        ]
      }
    }
