apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak
  labels:
    app: keycloak
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keycloak
  template:
    metadata:
      labels:
        app: keycloak
    spec:
      containers:
      - name: keycloak
        image: quay.io/keycloak/keycloak:26.1
        args:
          - start-dev
          - --import-realm
        envFrom:
        - configMapRef:
            name: keycloak-config
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 2000m
            memory: 2Gi
        livenessProbe:
          httpGet:
            path: /health/live
            port: 9000
          initialDelaySeconds: 20
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health/ready
            port: 9000
          initialDelaySeconds: 20
          periodSeconds: 10
        startupProbe:
          httpGet:
            path: /health/started
            port: 9000
          initialDelaySeconds: 20
          periodSeconds: 10
          failureThreshold: 20
        volumeMounts:
        - name: keycloak-config
          mountPath: /opt/keycloak/data/import/realm.json
          subPath: realm.json
          readOnly: true
        - name: keycloak-data-pvc
          mountPath: /opt/jboss/keycloak/standalone/data
      volumes:
      - name: keycloak-config
        configMap:
          name: keycloak-config
      - name: keycloak-data-pvc
        persistentVolumeClaim:
          claimName: keycloak-data-pvc

