apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: objectstore
  labels:
    app: objectstore
spec:
  rules:
  - host: api.objectstore.docker.localhost
    http:
      paths:
        - path: /
          pathType: ImplementationSpecific
          backend:
              service:
                name: objectstore
                port:
                  name: api
  - host: console.objectstore.docker.localhost
    http:
      paths:
        - path: /
          pathType: ImplementationSpecific
          backend:
              service:
                name: objectstore
                port:
                  name: console
