apiVersion: v1
kind: Service
metadata:
  name: objectstore
  labels:
    app: objectstore
spec:
  selector:
    app: objectstore
  ports:
  - name: api
    port: 9000
    targetPort: api
    protocol: TCP
  - name: console
    port: 9001
    targetPort: console
    protocol: TCP
  type: ClusterIP
