apiVersion: v1
kind: ConfigMap
metadata:
  name: kdex-proxy-config
  labels:
    app: kdex-proxy
data:
  upstream_address: "liferay-helm.liferay-system:8080"
  upstream_healthz_path: "/c/portal/robots"
  mapped_headers: "Authorization,Content-Type,Host,Origin,User-Agent"