apiVersion: v1
kind: ConfigMap
metadata:
  name: kdex-proxy-config
  labels:
    app: kdex-proxy
data:
  upstream_address: "liferay-helm.liferay-system:8080"
  upstream_healthz_path: "/c/portal/robots"
  module_imports: |
    {
      "imports": {
        "@kdex-ui": "@kdex-ui/index.js"
      }
    }
  module_body: |
    import '@kdex-ui';
