apiVersion: v1
kind: ConfigMap
metadata:
  name: coredns
  namespace: kube-system
data:
  Corefile: |
    .:53 {
        errors
        health
        ready
        kubernetes cluster.local in-addr.arpa ip6.arpa {
          pods insecure
          fallthrough in-addr.arpa ip6.arpa
        }
        # rewrite stop {
        #   name keycloak.docker.localhost keycloak.default.svc.cluster.local
        # }
        # rewrite stop {
        #   name proxy.docker.localhost kdex-proxy.default.svc.cluster.local
        # }
        rewrite stop {
          name regex (.*)\.docker\.localhost {1}.default.svc.cluster.local
          answer name (.*)\.default\.svc\.cluster\.local {1}.docker.localhost
        }
        hosts /etc/coredns/NodeHosts {
          ttl 60
          reload 15s
          fallthrough
        }
        prometheus :9153
        forward . /etc/resolv.conf
        cache 30
        loop
        reload
        loadbalance
        import /etc/coredns/custom/*.override
    }
    import /etc/coredns/custom/*.server
  NodeHosts: |
    172.20.0.2 k3d-playground-server-0
