apiVersion: v1
kind: ConfigMap
metadata:
  name: kdex-proxy-config
  labels:
    app: kdex-proxy
data:
  ALWAYS_APPEND_SLASH: "true"
  AUTHENTICATE_HEADER: "WWW-Authenticate"
  AUTHORIZATION_HEADER: "Authorization"
  AUTHENTICATE_STATUS_CODE: "401"
  AUTH_VALIDATOR: "oauth"
  OAUTH_REALM: "KDEX Proxy"
  OAUTH_SERVER_URL: "http://keycloak.docker.localhost"
  OAUTH_CLIENT_ID: "kdex-proxy"
  OAUTH_CLIENT_SECRET: "0fxGz4vzlF3tINhDdcoFmGipsl9QLfnZ"
  OAUTH_DUMP_CLAIMS: "true"
  OAUTH_REDIRECT_URI: "http://proxy.docker.localhost/~/o/oauth/callback"
  OAUTH_SCOPES: "openid profile email"
  PROTECTED_PATHS: "/private"
  UPSTREAM_ADDRESS: "sample-site"
  UPSTREAM_HEALTHZ_PATH: "/"

  # Configure the apps that will be embedded in the proxy
  apps: |
    [
      {
        "alias": "ke",
        "address": "sample-app.docker.localhost",
        "element": "kdex-example",
        "path": "app.js",
        "targets": [
          {
            "path": "/posts",
            "containerId": "main"
          }
        ],
        "requiredScopes": []
      }
    ]

  # The package.json file for the proxy
  package.json: |
    {
      "name": "tmp",
      "version": "1.0.0",
      "dependencies": {
      }
    }
