apiVersion: v1
kind: ConfigMap
metadata:
  name: proxy-config
  labels:
    app: proxy
data:
  proxy.config: |
    apps:
    - alias: ke
      address: sample-app.docker.localhost
      element: kdex-example
      path: app.js
      targets:
      - path: /posts
        container_id: main
    - alias: k2
      address: sample-app.docker.localhost
      element: kdex-example
      path: app.js
      targets:
      - path: /admin
        container_id: main
    authn:
      auth_validator: oauth
      login:
        path: /~/oauth/login
        label: Login
        query: nav a[href="/signin/"]
      logout:
        path: /~/oauth/logout
        label: Logout
        query: nav a[href="/signin/"]
      oauth:
        auth_server_url: http://keycloak.docker.localhost
        client_id: kdex-proxy
        client_secret: FZd8qsIive63taCdU3y3fARCCMU1SCUS
        dump_claims: true
        redirect_uri: http://proxy.docker.localhost/~/oauth/callback
    authz:
      static:
        permissions:
        - resource: page:/*
          action: view
          principal: user
        - resource: page:/
          action: view
          principal: anonymous
        - resource: page:/~/state
          action: view
          principal: anonymous
        - resource: page:/css/*
          action: view
          principal: anonymous
        - resource: page:/favicon*
          action: view
          principal: anonymous
        - resource: page:/foo/*
          action: view
          principal: anonymous
        - resource: page:/posts/*
          action: view
          principal: anonymous
        - resource: page:/robots.txt
          action: view
          principal: anonymous
    expressions:
      principal: "data.preferred_username"
      roles: "data.realm_access.roles"
    navigation:
      nav_items_query: //nav//li[not(contains(@class,'Banner-item--title')) and contains(@class,'Banner-item')]
      nav_item_fields:
        href: a/@href
        label: a/text()
      nav_item_template: |
        <li class="Banner-item">
          <a class="Banner-link u-clickable" href="{{ .href }}">{{ .label }}</a>
        </li>
      template_paths:
      - href: /foo
        label: Foo
        template: /template1
        weight: 0.5
      - href: /admin
        label: Admin
        template: /template1
        weight: 1.5
    proxy:
      always_append_slash: true
      append_index: true
      # upstream_address: sample-site
      upstream_address: objectstore-api.docker.localhost:9000
      upstream_healthz_path: /site/public/index.html
      upstream_prefix: /site/public

  # The package.json file for the proxy
  package.json: |
    {
      "name": "tmp",
      "version": "1.0.0",
      "dependencies": {
      }
    }
