apiVersion: v1
kind: ConfigMap
metadata:
  name: kdex-proxy-config
  labels:
    app: kdex-proxy
data:
  ALWAYS_APPEND_SLASH: "true"
  AUTHENTICATE_HEADER: "WWW-Authenticate"
  AUTHORIZATION_HEADER: "Authorization"
  AUTHENTICATE_STATUS_CODE: "401"
  AUTH_VALIDATOR: "static_basic_auth"
  PROTECTED_PATHS: "/private"
  STATIC_BASIC_AUTH_PASSWORD: "testpassword"
  STATIC_BASIC_AUTH_USERNAME: "testuser"
  UPSTREAM_ADDRESS: "sample-site"
  UPSTREAM_HEALTHZ_PATH: "/"

  # Configure the apps that will be embedded in the proxy
  apps: |
    [
      {
        "alias": "ke",
        "address": "sample-app.docker.localhost",
        "element": "kdex-example",
        "path": "app.js",
        "targets": [
          {
            "path": "/posts",
            "containerId": "main"
          }
        ],
        "requiredScopes": []
      }
    ]

  # The package.json file for the proxy
  package.json: |
    {
      "name": "tmp",
      "version": "1.0.0",
      "dependencies": {
      }
    }
