apiVersion: v1
kind: ConfigMap
metadata:
  name: kdex-proxy-config
  labels:
    app: kdex-proxy
data:
  config.json: |
    {
      "apps": [
        {
          "alias": "ke",
          "address": "sample-app.docker.localhost",
          "element": "kdex-example",
          "path": "app.js",
          "targets": [
            {
              "path": "/posts",
              "container_id": "main"
            }
          ]
        }
      ],
      "authn": {
        "authenticate_header": "WWW-Authenticate",
        "authorization_header": "Authorization",
        "authenticate_status_code": 401,
        "auth_validator": "oauth",
        "realm": "KDEX Proxy",
        "protected_paths": [
          "/private"
        ],
        "oauth": {
          "auth_server_url": "http://keycloak.docker.localhost",
          "client_id": "kdex-proxy",
          "client_secret": "FZd8qsIive63taCdU3y3fARCCMU1SCUS",
          "dump_claims": true,
          "redirect_uri": "http://proxy.docker.localhost/~/o/oauth/callback",
          "scopes": [
            "openid",
            "profile",
            "email"
          ]
        }
      },
      "proxy": {
        "always_append_slash": true,
        "upstream_address": "sample-site",
        "upstream_healthz_path": "/"
      }
    }

  # The package.json file for the proxy
  package.json: |
    {
      "name": "tmp",
      "version": "1.0.0",
      "dependencies": {
      }
    }
