apiVersion: v1
kind: ConfigMap
metadata:
  name: kdex-proxy-config
  labels:
    app: kdex-proxy
data:
  always_append_slash: "true"
  authenticate_header: "WWW-Authenticate"
  authorization_header: "Authorization"
  authenticate_status_code: "401"
  auth_validator: "static_basic_auth"
  protected_paths: "/private"
  password: "testpassword"
  upstream_address: "sample-site"
  upstream_healthz_path: "/"
  username: "testuser"
  # TODO: design how apps are tracked and assigned to the proxy for embedding
  # This array is just a preliminary approach to how they might be modelled and discovered by the proxy
  apps: |
    [
      {
        "alias": "ke",
        "address": "sample-app.docker.localhost",
        "element": "kdex-example",
        "path": "app.js",
        "targets": [
          {
            "path": "/posts",
            "containerId": "main"
          }
        ],
        "requiredScopes": []
      }
    ]
  package.json: |
    {
      "name": "tmp",
      "version": "1.0.0",
      "dependencies": {
      }
    }
