apiVersion: apps/v1
kind: Deployment
metadata:
  name: kdex-proxy
  labels:
    app: kdex-proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kdex-proxy
  template:
    metadata:
      labels:
        app: kdex-proxy
    spec:
      initContainers:
      - name: package-dependencies
        image: registry:5000/package-dependencies
        command:
        - "sh"
        - "-c"
        - |
          cp kdex-ui.tgz /tmp
          cp package.json /tmp
          cd /tmp
          npm i
          npm i ./kdex-ui.tgz
          npm i --save-dev esbuild
          npx esbuild node_modules/**/*.js --allow-overwrite --outdir=node_modules --define:process.env.NODE_ENV=\"production\"
          mv node_modules/* /modules
          ls -l /modules
        volumeMounts:
        - mountPath: /modules
          name: kdex-proxy-pvc
        - mountPath: /app/package.json
          name: kdex-proxy-config
          subPath: package.json
        resources:
          limits:
            cpu: 500m
            memory: 256Mi
      containers:
      - name: bash
        # For testing. So we can exec in to see the contents of /modules.
        image: bash
        command:
        - "/usr/local/bin/bash"
        - "-c"
        - |
          trap 'echo "Received signal, exiting..."; exit 0' SIGINT SIGTERM
          sleep infinity &
          wait $!
        resources:
          limits:
            cpu: 500m
            memory: 256Mi
        volumeMounts:
        - mountPath: /modules
          name: kdex-proxy-pvc
        - mountPath: /etc/kdex/apps
          name: kdex-proxy-config
          subPath: apps
        - mountPath: /etc/kdex/module_body
          name: kdex-proxy-config
          subPath: module_body
      - name: proxy
        image: registry:5000/kdex-tech/proxy:latest
        ports:
        - containerPort: 8080
        env:
        - name: ALWAYS_APPEND_SLASH
          valueFrom:
            configMapKeyRef:
              name: kdex-proxy-config
              key: always_append_slash
        - name: AUTH_VALIDATOR
          valueFrom:
            configMapKeyRef:
              name: kdex-proxy-config
              key: auth_validator
        - name: STATIC_BASIC_AUTH_USERNAME
          valueFrom:
            configMapKeyRef:
              name: kdex-proxy-config
              key: username
        - name: STATIC_BASIC_AUTH_PASSWORD
          valueFrom:
            configMapKeyRef:
              name: kdex-proxy-config
              key: password
        - name: PROTECTED_PATHS
          valueFrom:
            configMapKeyRef:
              name: kdex-proxy-config
              key: protected_paths
        - name: USERNAME
          valueFrom:
            configMapKeyRef:
              name: kdex-proxy-config
              key: username
        - name: PASSWORD
          valueFrom:
            configMapKeyRef:
              name: kdex-proxy-config
              key: password
        - name: UPSTREAM_ADDRESS
          valueFrom:
            configMapKeyRef:
              name: kdex-proxy-config
              key: upstream_address
        - name: UPSTREAM_HEALTHZ_PATH
          valueFrom:
            configMapKeyRef:
              name: kdex-proxy-config
              key: upstream_healthz_path
        resources:
          limits:
            cpu: 500m
            memory: 256Mi
        livenessProbe:
          httpGet:
            path: /~/p
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /~/p
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 10
        volumeMounts:
        - mountPath: /modules
          name: kdex-proxy-pvc
        - mountPath: /etc/kdex/apps
          name: kdex-proxy-config
          subPath: apps
        - mountPath: /etc/kdex/module_body
          name: kdex-proxy-config
          subPath: module_body
      volumes:
      - name: kdex-proxy-pvc
        persistentVolumeClaim:
          claimName: kdex-proxy-pvc
      - name: kdex-proxy-config
        configMap:
          name: kdex-proxy-config
      securityContext:
        fsGroup: 65532
        runAsNonRoot: true
        runAsUser: 65532
        runAsGroup: 65532
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: kdex-proxy-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
