apiVersion: apps/v1
kind: Deployment
metadata:
  name: proxy
  labels:
    app: proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: proxy
  template:
    metadata:
      labels:
        app: proxy
    spec:
      initContainers:
      - name: package-dependencies
        image: registry:5000/package-dependencies
        command:
        - "sh"
        - "-c"
        - |
          [ $(wc -l < /modules/sums.txt) -eq 2 ] && sha256sum -c /modules/sums.txt 2&>/dev/null
          if [ $? -ne 0 ]; then
            rm -rf /modules/* 2&>/dev/null
            cp kdex-ui.tgz /tmp
            cp package.json /tmp
            (
              cd /tmp
              npm i
              npm i ./kdex-ui.tgz
              npm i --save-dev esbuild
              npx esbuild node_modules/**/*.js --allow-overwrite --outdir=node_modules --define:process.env.NODE_ENV=\"production\"
              cp -r node_modules/* /modules
            )
            sha256sum kdex-ui.tgz package.json > /modules/sums.txt
            ls -l /modules
          fi
        volumeMounts:
        - mountPath: /cache
          name: proxy-pvc
          subPath: cache
        - mountPath: /modules
          name: proxy-pvc
          subPath: modules
        - mountPath: /app/package.json
          name: proxy-config
          subPath: package.json
        resources:
          limits:
            cpu: 500m
            memory: 256Mi
      containers:
      - name: bash
        # For testing. So we can exec in to see the contents of /modules.
        image: bash
        command:
        - "/usr/local/bin/bash"
        - "-c"
        - |
          trap 'echo "Received signal, exiting..."; exit 0' SIGINT SIGTERM
          sleep infinity &
          wait $!
        resources:
          limits:
            cpu: 500m
            memory: 256Mi
        volumeMounts:
        - mountPath: /modules
          name: proxy-pvc
          subPath: modules
        - mountPath: /etc/kdex-proxy/config.json
          name: proxy-config
          subPath: config.json
      - name: proxy
        image: registry:5000/kdex-tech/proxy:latest
        ports:
        - containerPort: 8080
        resources:
          limits:
            cpu: 500m
            memory: 256Mi
        livenessProbe:
          httpGet:
            path: /~/p
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /~/p
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 10
        volumeMounts:
        - mountPath: /modules
          name: proxy-pvc
          subPath: modules
        - mountPath: /etc/kdex-proxy/proxy.config
          name: proxy-config
          subPath: proxy.config
      volumes:
      - name: proxy-pvc
        persistentVolumeClaim:
          claimName: proxy-pvc
      - name: proxy-config
        configMap:
          name: proxy-config
      securityContext:
        fsGroup: 65532
        runAsNonRoot: true
        runAsUser: 65532
        runAsGroup: 65532
