apiVersion: v1
kind: Service
metadata:
  name: proxy
  labels:
    app: proxy
spec:
  selector:
    app: proxy
  ports:
    - name: http
      port: 80
      targetPort: main
      protocol: TCP
    - name: debug
      port: 2345
      targetPort: debug
      protocol: TCP
  type: ClusterIP 